from bs4 import BeautifulSoup
from oscopilot.utils.llms import OpenAI

def question_html(html_path, user_question):
    """
    Answers a user-provided question based on the content of an HTML file.

    Args:
        html_path (str): The path to the HTML file to analyze.
        user_question (str): The question the user wants to ask about the HTML content.

    Returns:
        str: The response to the user's question generated by OpenAI.
    """
    try:
        # Read the HTML file
        with open(html_path, 'r', encoding='utf-8') as file:
            html_content = file.read()

        # Extract text from HTML using BeautifulSoup
        soup = BeautifulSoup(html_content, 'html.parser')
        text_content = soup.get_text(separator=' ', strip=True)

        # Initialize OpenAI instance
        llm = OpenAI()

        # Create the messages for OpenAI chat
        messages = [
            {"role": "system", "content": "You are a knowledgeable assistant that answers questions based on provided HTML content."},
            {"role": "user", "content": f"The following is the extracted content from an HTML file:\n{text_content}\n\nUser Question: {user_question}"}
        ]

        # Get the response from OpenAI
        response = llm.chat(messages)

        return response

    except FileNotFoundError:
        return f"Error: The file at {html_path} was not found."
    except Exception as e:
        # Handle other exceptions
        return f"An error occurred: {str(e)}"
