def summarize_html(html_path, user_requirement="Summarize the content"):
    from bs4 import BeautifulSoup
    from oscopilot.utils.llms import OpenAI
    """
    Summarizes the content of an HTML file based on the user's requirement.

    Args:
        html_path (str): The path to the HTML file to summarize.
        user_requirement (str): Additional instructions or requirements for the summary.
                                Defaults to "Summarize the content".

    Returns:
        str: The summary of the HTML content generated by OpenAI.
    """
    try:
        # Read the HTML file
        with open(html_path, 'r', encoding='utf-8') as file:
            html_content = file.read()

        # Extract text from HTML using BeautifulSoup
        soup = BeautifulSoup(html_content, 'html.parser')
        text_content = soup.get_text(separator=' ', strip=True)

        # Initialize OpenAI instance
        llm = OpenAI()

        # Create the messages for OpenAI chat
        messages = [
            {"role": "system", "content": "You are a helpful assistant that processes HTML content."},
            {"role": "user", "content": f"{user_requirement}: {text_content}"}
        ]

        # Get the response from OpenAI
        response = llm.chat(messages)

        return response

    except Exception as e:
        # Handle errors (e.g., file not found, OpenAI API errors)
        return f"An error occurred: {str(e)}"